### PR TITLE
compat: add compat code for RHEL 9.2 kernels

### PR DESCRIPTION
**Pull request by ryno-swart-corigine**
Update the RHEL_RELEASE version compatibility ranges to work with RHEL 9.2 kernel variants.

### CODE REVIEW

**Review by jcoetzee-corigine — APPROVED** [review]
Thanks Ryno. 
I usually make the PR in private, push to public for build checking, and Louis then merges, and propagates. Not sure if the current workflow is a problem, but I'm sure he will tell you if it is.
```
Reviewed-by: Jaco Coetzee <jaco.coetzee@corigine.com>
```

**Review by louis-peens — CHANGES_REQUESTED** [review]
> I usually make the PR in private, push to public for build checking, and Louis then merges, and propagates. Not sure if the current workflow is a problem, but I'm sure he will tell you if it is.

This is indeed the recommended workflow. This time I will do it the other way around, but please remember for next time.

I don't think this kernel is in a RHEL 9.2 variant? This rather moving towards RHEL 9.3. I think this specific patch is probably more in the line of this patch:
```
compat: add support for RHEL 9 kernel >=5.14.0-305
```
The RHEL 8.7 and RHEL 8.8 patches which recently merged were the first time support for _any_ of those kernels got added so that is why their style differs slightly, but [RHEL 9.2](https://github.com/Corigine/nfp-drv-kmods/actions/runs/5091557034/jobs/9151735548) compile works fine **without** this patch. Please update the summary and commit message to match the example above a bit closer. The patch code itself looks good to me, thanks.

**Comment by ryno-swart-corigine** [comment]
> This is indeed the recommended workflow. This time I will do it the other way around, but please remember for next time.

Sorry about that. I misunderstood what the ticket meant by "public-main". Won't happen again.

> Please update the summary and commit message to match the example above a bit closer.

Done.

**Review by louis-peens — APPROVED** [review]
Thanks for the updates Ryno, merging.

**Pull request merged**
